"""empty message

Revision ID: bb7289d88b49
Revises: 214dc7418373
Create Date: 2018-08-31 20:04:49.122687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7289d88b49'
down_revision = '214dc7418373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'time')
    # ### end Alembic commands ###
